name: hsa
description: HSA - Home Services Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  intl: ^0.20.2
  shared_preferences: ^2.3.2
  supabase_flutter: ^2.6.0
  provider: ^6.1.2
  fl_chart: ^1.1.1
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true